name: ece143
channels:
  - conda-forge
dependencies:
  - ca-certificates=2021.10.8=h4653dfc_0
  - certifi=2021.10.8=py38h10201cd_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - freetype=2.10.4=h17b34a0_1
  - jbig=2.1=h3422bc3_2003
  - jpeg=9d=h27ca646_0
  - kiwisolver=1.3.2=py38h1670459_1
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=12_osxarm64_openblas
  - libcblas=3.9.0=12_osxarm64_openblas
  - libcxx=12.0.1=h168391b_0
  - libdeflate=1.8=h3422bc3_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=12_osxarm64_openblas
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libtiff=4.3.0=h74060c4_2
  - libwebp-base=1.2.1=h3422bc3_0
  - libzlib=1.2.11=hee7b306_1013
  - llvm-openmp=12.0.1=hf3c4609_1
  - lz4-c=1.9.3=hbdafb3b_1
  - matplotlib=3.4.3=py38h150bfb4_1
  - matplotlib-base=3.4.3=py38hb140015_1
  - ncurses=6.2=h9aa5885_4
  - numpy=1.21.4=py38hbf7bb01_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=3.0.0=h3422bc3_2
  - pandas=1.3.4=py38h3777fb4_1
  - patsy=0.5.2=pyhd8ed1ab_0
  - pillow=8.4.0=py38h02acf36_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pyparsing=3.0.5=pyhd8ed1ab_0
  - python=3.8.12=hd949e87_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=hedafd6a_0
  - scipy=1.7.2=py38hd0c9ec0_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=58.5.3=py38h10201cd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h72a2b83_2
  - statsmodels=0.13.0=py38h691f20f_1
  - tk=8.6.11=he1e0b03_1
  - tornado=6.1=py38hea4295b_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h642e427_1
  - zlib=1.2.11=hee7b306_1013
  - zstd=1.5.0=h861e0a7_0
